[[language]]
name = "python"
language-id = "python"
auto-format = true
language-servers = ["ruff", "pyright"]
file-types = ["py", "ipynb"]
comment-token = "#"
shebangs = ["python"]

# [language-server.ty]
# command = "ty"
# args = ["server"]

# [language-server.lsp-ai]
# command = "lsp-ai"
#

[[language]]
name = "bash"
file-types = ["sh", "bash", "zsh", "conf", "tmux.conf", ".tmux.conf"]
