set -g prefix C-a

unbind C-b

bind C-a send-prefix

set -g status-right ' #{?client_prefix,#[reverse]<Prefix>#[noreverse] ,}"#{=21:pane_title}" %H:%M %d-%b-%y'

set -g mouse on

bind -n C-h select-pane -L
bind -n C-j select-pane -D
bind -n C-k select-pane -U
bind -n C-l select-pane -R

set -g window-active-style 'fg=default,bg=terminal'
set -g window-style 'fg=default,bg=terminal'

# Set the active pane border color (e.g., blue)
set -g pane-active-border-style fg=yellow

# # Set the inactive pane border color (e.g., grey)
set -g pane-border-style fg=brightblack
set -g pane-border-lines heavy
set -g pane-border-indicators off
set -g pane-border-format ""

set -g pane-border-status top

set -g status-position top

# split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

bind r source-file ~/.tmux.conf
